### ISSUE TITLE
DB-ABS

### ISSUE THREAD

**Issue by robotateme** [hophiphip/bruh#2]
https://github.com/hophiphip/bruh/blob/7ece9bc62b3a65a370bc92451ea30bb3184616e5/docks/models.drawio#L1

Description можно TEXT делать. Уточни в PostgreSQL по поводу Varchar vs Text.

Как юзеру узнать, кто он (фирма или юзер)? Сейчас в задаче нет авторизации для обычных пользователей. Это конечно не значит что в будущем не будет личного кабинета для постоянных клиентов. Но и о том что он будет никто не говорит) 

На мой взгляд, довольно запутанна абстракция с многие-ко-многим. У нас есть клиенты и фирмы, от фирм есть услуги. Услуги имеют категории. В юзере можно сделать полиморфную связь, но стоит ли это того? По идее можно хранить все заявки и транзакции клиентов. Как тебе такое?)

**Comment by hophiphip** [comment]
- TEXT seems better for this purpose.
- DB internal structure is not final and will be updated as I go further.

**Comment by hophiphip** [comment]
Поточнее распишу:
1. TEXT vs varchar(а не varchar(n)): в PostgreSQL они - одно и тоже, а внутри они все `varlena`. По перфомансу нет разницы. Но TEXT лаконичнее звучит. 
2. `Как юзеру узнать, кто он` - изначально предполагалось, что поля с FK обнуляемые и только одно из них не null - но это не совсем хорошо.
3. `На мой взгляд, довольно запутана абстракция с многие-ко-многим` - да. Поэтому я решил особо много над этим не думать и делать всё по мере необходимости. Потому что пока ещё не понятно как я хочу и хочу ли вообще реализовывать `i18n` и прочие фичи.
