### ISSUE TITLE
метод first()?

### ISSUE THREAD

**Issue by robotateme** [hophiphip/bruh#3]
https://github.com/hophiphip/bruh/blob/87aeda832dff08a4ab0e83f96525ac6091e78ea4/bruh/app/Models/Offer.php#L86

Тут не понятно зачем first, если у тебя один страховщик. По идее тут и не нужен метод этот.

**Comment by hophiphip** [comment]
1.
```php
Offer::find(1)->getInsurer() // type: Illuminate\Database\Eloquent\Relations\BelongsTo
```

2.
```php
Offer::find(1)->getInsurer()->get() // type: Illuminate\Database\Eloquent\Collection
```

3.
```php
 Offer::find(1)->getInsurer()->get()->first() // type: App\Models\Insurer
```

**Comment by hophiphip** [comment]
Метод `first` нужен чтобы из Collection получить Insurer

**Comment by hophiphip** [comment]
Ладно, я что-то туплю. Я лишнее пишу. Достаточно: 
```php
Offer::find(1)->insurer()->first()
```
или
```php
Offer::find(1)->insurer()->firstOrFail()
```
