### ISSUE TITLE
Dictionary

### ISSUE THREAD

**Issue by robotateme** [hophiphip/bruh#4]
https://github.com/hophiphip/bruh/blob/87aeda832dff08a4ab0e83f96525ac6091e78ea4/bruh/app/Models/Offer.php#L26

Можешь создать отдельные словари Dictionary. Не забивай сущности лишней логикой.

**Comment by hophiphip** [comment]
Да, ну либо `json text array`. Но я подумывал над добавлением `i18n` и ещё не проверял, что лучше будет сочетаться с `hstore` в postgresql.

**Comment by hophiphip** [comment]
https://github.com/hophiphip/bruh/commit/666ce173600afa55faad9e0932d68657413863c0
