### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by robotateme** [hophiphip/bruh#5]
https://github.com/hophiphip/bruh/blob/752cce8943166ebe961d6be695e28c2fd7d4d8d5/bruh/app/Http/Controllers/AuthController.php#L31
Это можно в LoginRequest сбросить.

https://github.com/hophiphip/bruh/blob/752cce8943166ebe961d6be695e28c2fd7d4d8d5/bruh/app/Http/Controllers/AuthController.php#L38
Можешь установить "vladimir-yuldashev/laravel-queue-rabbitmq" для того чтобы он сгенерирует комменты необходимые

https://github.com/hophiphip/bruh/blob/82313c4e1ed1e40481117ee46aab0d2a89d49ec8/bruh/app/Models/User.php#L100
Это надо перенести в Event>Listener::handle

https://github.com/hophiphip/bruh/blob/e859cbb35aefd3d9a185b63381b35a05355001cd/bruh/app/Http/Controllers/InsurerController.php#L17
Можешь брать юзера из $request->user(). 

https://github.com/hophiphip/bruh/blob/752cce8943166ebe961d6be695e28c2fd7d4d8d5/bruh/app/Http/Controllers/AuthController.php#L66
Можешь создать AuthService для бизнес-логики.

**Comment by hophiphip** [comment]
Added `PostLoginRequest` and `PostSignUpRequest` 

https://github.com/hophiphip/bruh/commit/eeba2c9503e5e5dbc6d6044479fa4e0d015744d2

**Comment by hophiphip** [comment]
`vladimir-yuldashev/laravel-queue-rabbitmq` - уже был установлен

https://github.com/hophiphip/bruh/blob/eeba2c9503e5e5dbc6d6044479fa4e0d015744d2/bruh/composer.json#L23

Не совсем понимаю суть проблемы

**Comment by hophiphip** [comment]
Добавлены `Event`-ы

https://github.com/hophiphip/bruh/commit/babeec8b5662c22edcbcdb94922d8d0e115311cc

Пока не уверен, что это лучшее решение - `Events` вызывают `Jobs`, тогда какой смысл в `Jobs` ?

**Comment by hophiphip** [comment]
`User` теперь берется из `$request`

https://github.com/hophiphip/bruh/commit/f6f6ec9c2da213b85084bfde9941cd1e48623e32

**Comment by robotateme** [comment]
> `vladimir-yuldashev/laravel-queue-rabbitmq` - уже был установлен
> 
> https://github.com/hophiphip/bruh/blob/eeba2c9503e5e5dbc6d6044479fa4e0d015744d2/bruh/composer.json#L23
> 
> Не совсем понимаю суть проблемы

Пардон, https://github.com/barryvdh/laravel-ide-helper не то скопировал.

**Comment by robotateme** [comment]
> Добавлены `Event`-ы
> 
> [babeec8](https://github.com/hophiphip/bruh/commit/babeec8b5662c22edcbcdb94922d8d0e115311cc)
> 
> Пока не уверен, что это лучшее решение - `Events` вызывают `Jobs`, тогда какой смысл в `Jobs` ?

У Events есть Listeners, их можно джобать. Как-то так, на самом деле. Джоба могут дипатчится и без Events. Почитай доку,  сам точно не вспомню

**Comment by robotateme** [comment]
Вся суть, избавлять контроллеры от бизнес-логики. Отделять бизнес-логику от инфраструктуры фреймворка. Стараться отделять.

**Comment by hophiphip** [comment]
> > Добавлены `Event`-ы
> > [babeec8](https://github.com/hophiphip/bruh/commit/babeec8b5662c22edcbcdb94922d8d0e115311cc)
> > Пока не уверен, что это лучшее решение - `Events` вызывают `Jobs`, тогда какой смысл в `Jobs` ?
> 
> У Events есть Listeners, их можно джобать. Как-то так, на самом деле. Джоба могут дипатчится и без Events. Почитай доку, сам точно не вспомню

 1. Как и `Jobs`, `Listeners` могут имплементировать интерфейс `ShouldQueue` (+ трэйты) - это понятно.

 2.
 - Плюс `Events` в том, что у них может быть много `Listener`-ов - которые не обязательно должны явно вызываться.
 - `Jobs` должны вызываться явно, как я это и делал в методе класса `User` - и этого было достаточно в данном случае. Так было более читаемо.

**Comment by robotateme** [comment]
> > > Добавлены `Event`-ы
> > > [babeec8](https://github.com/hophiphip/bruh/commit/babeec8b5662c22edcbcdb94922d8d0e115311cc)
> > > Пока не уверен, что это лучшее решение - `Events` вызывают `Jobs`, тогда какой смысл в `Jobs` ?
> > 
> > 
> > У Events есть Listeners, их можно джобать. Как-то так, на самом деле. Джоба могут дипатчится и без Events. Почитай доку, сам точно не вспомню
> 
> 1. Как и `Jobs`, `Listeners` могут имплементировать интерфейс `ShouldQueue` (+ трэйты) - это понятно.
> 
> * Плюс `Events` в том, что у них может быть много `Listener`-ов - которые не обязательно должны явно вызываться.
> * `Jobs` должны вызываться явно, как я это и делал в методе класса `User` - и этого было достаточно в данном случае. Так было более читаемо.

https://github.com/hophiphip/bruh/blob/82313c4e1ed1e40481117ee46aab0d2a89d49ec8/bruh/app/Models/User.php#L97
Вообще весь этот метод вынести в Listener. В модели ему не место. В этом смысл.

**Comment by hophiphip** [comment]
> > `vladimir-yuldashev/laravel-queue-rabbitmq` - уже был установлен
> > https://github.com/hophiphip/bruh/blob/eeba2c9503e5e5dbc6d6044479fa4e0d015744d2/bruh/composer.json#L23
> > 
> > Не совсем понимаю суть проблемы
> 
> Пардон, https://github.com/barryvdh/laravel-ide-helper не то скопировал.

PHP Doc

https://github.com/hophiphip/bruh/commit/c326162ec9a8a428d2fd605ac69d57a08c200643

**Comment by hophiphip** [comment]
> > > > Добавлены `Event`-ы
> > > > [babeec8](https://github.com/hophiphip/bruh/commit/babeec8b5662c22edcbcdb94922d8d0e115311cc)
> > > > Пока не уверен, что это лучшее решение - `Events` вызывают `Jobs`, тогда какой смысл в `Jobs` ?
> > > 
> > > 
> > > У Events есть Listeners, их можно джобать. Как-то так, на самом деле. Джоба могут дипатчится и без Events. Почитай доку, сам точно не вспомню
> > 
> > 
> > 
> > 1. Как и `Jobs`, `Listeners` могут имплементировать интерфейс `ShouldQueue` (+ трэйты) - это понятно.
> > 
> > 
> > * Плюс `Events` в том, что у них может быть много `Listener`-ов - которые не обязательно должны явно вызываться.
> > * `Jobs` должны вызываться явно, как я это и делал в методе класса `User` - и этого было достаточно в данном случае. Так было более читаемо.
> 
> https://github.com/hophiphip/bruh/blob/82313c4e1ed1e40481117ee46aab0d2a89d49ec8/bruh/app/Models/User.php#L97
> 
> Вообще весь этот метод вынести в Listener. В модели ему не место. В этом смысл.

Removed old code

https://github.com/hophiphip/bruh/commit/bdb46491525fa4ebb67de8e75f4cc4915187d238

**Comment by hophiphip** [comment]
> https://github.com/hophiphip/bruh/blob/752cce8943166ebe961d6be695e28c2fd7d4d8d5/bruh/app/Http/Controllers/AuthController.php#L66
> 
> Можешь создать AuthService для бизнес-логики.

https://github.com/hophiphip/bruh/commit/00875b4d08d4763b4983755ba3c72f60647aa670

Added custom `AuthService`
