### ISSUE TITLE
CodeReview

### ISSUE THREAD

**Issue by e-sau** [hophiphip/bruh#7]
https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Observers/OfferObserver.php#L37-L40
https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Observers/OfferRequestObserver.php#L37-L40

- пустой метод

https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Providers/DatabaseTableNamesProvider.php#L8-L15

- метод заехал в константы

https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Models/ClientLocation.php#L20-L36

- методы, свойства в перемешку

https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Utils/GetIpAddress.php#L11

- сравнение с true избыточно

https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Http/Controllers/Api/OfferController.php#L30

- в input можно передать дефолтное значение input($key, $default)

https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Http/Controllers/WebController.php#L28

- здесь фабрика или инстанс приложения вряд ли вернутся

**Общее**

- используй declare(strict_types=1)
- можно освежить знания PSR-1, PSR-12

**Comment by hophiphip** [comment]
> https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Observers/OfferObserver.php#L37-L40
> 
> https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Observers/OfferRequestObserver.php#L37-L40
> 
>     * пустой метод
> 
> 

0b23e3eb9ad5dab5cdf9e5add6bdde14c5147b8e

**Comment by hophiphip** [comment]
> https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Providers/DatabaseTableNamesProvider.php#L8-L15
> 
>     * метод заехал в константы
> 

5f388fdf8b7181cfa3ec7735c853206cc31f766a

**Comment by hophiphip** [comment]
> https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Models/ClientLocation.php#L20-L36
> 
>     * методы, свойства в перемешку
> 

1be320effe58c8a3bc9c40e09cc598973bdac815

**Comment by hophiphip** [comment]
> https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Utils/GetIpAddress.php#L11
> 
>     * сравнение с true избыточно
> 

96e10af56d9319f2e579891e4abab4e452676da2

**Comment by hophiphip** [comment]
> https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Http/Controllers/Api/OfferController.php#L30
> 
>     * в input можно передать дефолтное значение input($key, $default)
> 

9543a0ece453aa4412f1ae0f5255e79836dfbb54

**Comment by hophiphip** [comment]
> https://github.com/hophiphip/bruh/blob/20df52ba3280b83b8c8a603e5f573624d192a8c5/bruh/app/Http/Controllers/WebController.php#L28
> 
>     * здесь фабрика или инстанс приложения вряд ли вернутся
> 

c009ebd3bbdf701f10354193b51d806012b767f0

**Comment by hophiphip** [comment]
> **Общее**
> 
>     * используй declare(strict_types=1)
> 
>     * можно освежить знания PSR-1, PSR-12

ok
